[package]
name = "fuzzer"
version = "1.1.0"
authors = ["sam <sunhaoyl@outlook.com>"]
edition = "2018"

[dependencies]
core = {path="../core"}
executor = {path = "../executor"}
fots={path="../fots"}
serde ={ version= "1.0.110" ,features = ["derive"]}
bincode = "1.2.1"
lazy_static = "1.4.0"
tokio = {version="0.2.21",features=["full"]}
bytes = "0.5.4"
toml = "0.5.6"
structopt = {version="0.3.7",default-features=true}
exitcode = "1.1.2"
os_pipe = "0.9.1"
nix = "0.17.0"
itertools = "0.9.0"
chrono = { version = "0.4.10", features = ["serde"] }
serde_json = "1.0.53"
circular-queue = "0.2.3"
log = "0.4"
log4rs = "0.11.0"
lettre = { version = "0.9", optional = true }
lettre_email = { version = "0.9", optional = true }
native-tls = { version = "0.2.4", optional = true }
num_cpus = "1.0"

[features]
default = []
mail = ["lettre", "lettre_email", "native-tls"]
