name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: sudo apt update && sudo apt install gcc-multilib g++-multilib
    - name: tcc-0.9.27
      run: git clone https://github.com/TinyCC/tinycc.git tcc  && cd tcc && ./configure && make && sudo make install && cd ../
    - name: Build
      run: cargo build --verbose
